### ISSUE TITLE
How to force the selected products from cart component info ? 

### ISSUE THREAD

**Issue by cAstraea** [krzysu/reactjs-shopping-cart#1]
Hello , 
Trying to do some modifications to this to include a search and pagination with https://github.com/AdeleD/react-paginate
but having some problems           http://recordit.co/HXqQ20roh1

If I'm adding items to the cart and start a search the products lose the .added state which I guess it's expected ? 
I thought maybe to keep the state in localStorage and set the added state based on that but not sure how it would be possible? 

What would be the best way to remember the added state between searches and paginated results ?

**Comment by krzysu** [comment]
Hi, what you can find in this repo is only a demo, for real applications you should use props (not component state) and keep state of your application in some other place (i.e. in store, see redux https://egghead.io/courses/getting-started-with-redux)
