### ISSUE TITLE
Cart vulnerability

### ISSUE THREAD

**Issue by codebuzzer01** [krzysu/reactjs-shopping-cart#26]
We cannot increase or decrease the number of a same item which we want to add in our cart. It is limited to only addition or deletion of a single product.
![image](https://user-images.githubusercontent.com/52864294/95015447-97eb1c80-066a-11eb-872a-f2f3f2b1134f.png)

**Comment by krzysu** [comment]
This is a feature, not a bug ;)
 
And seriously, this is a demo project for educational purposes. I don't offer any support here. 
Feel free to add any feature you want in your own project which you based on this demo.
Have a nice day!
