### ISSUE TITLE
Reload browser, cart is not save

### ISSUE THREAD

**Issue by vndevil** [krzysu/reactjs-shopping-cart#3]
When reload or re-open browser, cart is not save

**Comment by krzysu** [comment]
Thank you for your feedback, but nowhere in the readme file is written that this feature exists. This is a simple demo project to show how to use react.js. It's not suitable for any serious use.
You are welcome to add saving cart state to storage and restoring it after page load.
I'm closing this issue for now (is it is not an issue, but feature request).
