### ISSUE TITLE
Card height can be made consistent.

### ISSUE THREAD

**Issue by bikkimahato** [krzysu/reactjs-shopping-cart#36]
For a better UI experience the card height should be consistent.
For example the Sessel Sofie card.
![image](https://user-images.githubusercontent.com/42492682/132977206-e7c99846-fa86-4320-be21-8b320a7bdbcd.png)

**Comment by Carlos-Gaxiola** [comment]
Hello, can I work on this?

**Comment by krzysu** [comment]
@Carlos-Gaxiola you can always fork this repo and change whatever you like, but I'm not accepting any PRs with new features here. This is read-only repo now.
